apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2-advertisement
  namespace: metallb
spec:
  ipAddressPools:
  - demo-pool
  nodeSelectors:
  - matchLabels:
      node-role.kubernetes.io/control-plane: ""
