apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: https://charts.jetstack.io
    targetRevision: "1.17.*"
    chart: cert-manager
    helm:
      parameters:
      - name: "crds.enabled"
        value: "true"
      - name: "crds.keep"
        value: "true"
      ignoreMissingValueFiles: false
  - path: 'deployments/cert-manager'
    repoURL: 'https://github.com/a-lohmann/terraform-talos-demo.git'
    targetRevision: 'main'

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
