apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default

  source:

  sources:
  - repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.13.0

    # helm specific config
    chart: ingress-nginx
    helm:
      #passCredentials: false # If true then adds --pass-credentials to Helm commands to pass credentials to all domains
      ## Extra parameters to set (same as setting through values.yaml, but these take precedence)
      parameters:
      - name: "controller.service.type"
        value: "LoadBalancer"
      #- name: "nginx-ingress.controller.service.annotations.external-dns\\.alpha\\.kubernetes\\.io/hostname"
      #  value: mydomain.example.com
      #- name: "ingress.annotations.kubernetes\\.io/tls-acme"
      #  value: "true"
      #  forceString: true # ensures that value is treated as a string

      ## Use the contents of files as parameters (uses Helm's --set-file)
      #fileParameters:
      #- name: config
      #  path: files/config.json

      ## Helm values files for overriding values in the helm chart
      ## The path is relative to the spec.source.path directory defined above
      #valueFiles:
      #- values-prod.yaml

      # Ignore locally missing valueFiles when installing Helm chart. Defaults to false
      ignoreMissingValueFiles: false
  - path: 'deployments/ingress-nginx'
    repoURL: 'https://github.com/a-lohmann/terraform-talos-demo.git'
    targetRevision: 'main'

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
